version: '2.2'
services:
  database:
    image: postgres:9.6.9-alpine
    environment:
      POSTGRES_DB: batch
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'pass'
    ports:
      - '5432:5432'